
    'Administratīvās lietas' => 'xxxx',
    'Civillietas' => 'xxxx',
    'Ekspertīzes un novērtēšana' => 'xxxx',
    'Ģimenes tiesības' => 'xxxx',
    'Grāmatvedības pakalpojumi' => 'xxxx',
    'Krimināllietas' => 'xxxx',
    'Līdzdalība darijumos' => 'xxxx',
    'Notāra pakalpojumi' => 'xxxx',
    'Parādu atgriešana' => 'xxxx',
    'Uzņēmumu juridiskā apkalpošana' => 'xxxx',
    'Uzņēmumu reģistrācija' => 'xxxx',
    'Vīzu un dokumentu noformēšana' => 'xxxx',
    'Cits' => 'xxxx',
